---
# file: roles/samba-install/tasks/main.yml

- name: install samba server
  apt:
    name:
      - samba
      - samba-common
      - samba-common-bin
      - tdb-tools
    state: present
    install_recommends: no
  with_items:
