---
# file roles/autoinstall-hauppauge-pvr/tasks/main.yml

- name: apt | install vdr-plugin-pvrinput if a haupauge pvr card is found
  apt:
    name: vdr-plugin-pvrinput
  when: '"0070:4000" in pci or "4444:0016" in pci'
  notify: [ 'Restart VDR' ]
