---
# file: yavdr07.yml
# this playbook sets up a complete yaVDR 0.7 installation

- name: set up yaVDR
  hosts: all
  become: true
  roles:
    - yavdr-xorg

  handlers:
    - include: handlers/main.yml
