---
# file: yavdr07.yml
# this playbook sets up a complete yaVDR 0.7 installation

- name: set up yaVDR
  hosts: all
  become: true
  roles:
     - yavdr-common             # install and configure the basic system
     - autoinstall-ubuntu-drivers # use ubuntu-drivers to install proprietary dirvers (e.g. nvidia, virtualbox)
     - vdr                      # install vdr and related packages
     - yavdr-network            # enable network client capabilities
     - samba-install            # install samba server
     - samba-config             # configure samba server
     - nfs-server               # install nfs server
     - yavdr-xorg               # graphical session
     - yavdr-remote             # remote configuration files, services and scripts
     - autoinstall-satip        # install vdr-plugin-satip if a Sat>IP server has been found
     - autoinstall-targavfd     # install vdr-plugin-targavfd if display is connected
     - autoinstall-imonlcd      # install vdr-plugin-imonlcd if a matchind display is connected
     #- autoinstall-pv350        # install vdr-plugin-pvr350 if a matching card is detected
     #- autoinstall-dvbsddevice  # install vdr-plugin-dvbsddevice if a matching card is detected
     - kodi
     - dvd
     - grub-config          # configure grub

  handlers:
    - include: handlers/main.yml
