- name: get information about usb and pci hardware and loaded kernel modules
  hardware_facts:
    usb: True
    pci: True
    modules: True
    gpus: True
    acpi_power_modes: True
  tags:
    - always

- debug:
    var: '{{ item }}'
    verbosity: 1
  with_items:
    - usb
    - pci
    - gpus
    - modules
    - acpi_power_modes
    - nvidia_detected
    - intel_detected
    - amd_detected
    - virtualbox_detected

- name: get detailed PCI device information
  pci_facts:
  tags:
    - always

- debug:
    var: pci_devices
    verbosity: 1

- name: known vdr output plugins
  set_fact:
    vdr_output_plugins:    
      - softhddevice
      - xineliboutput
      - xine
