---

- name: install pulseaudio
  apt:
    name: '{{ item }}'
    state: present
    install_recommends: no
  with_items:
    - pulseaudio
    - pavucontrol

- name: create /etc/asound.conf
  template:
    src: templates/alsa/asound.conf.j2
    dest: /etc/asound.conf
