---

- name: apt | install pulseaudio, pavucontrol and vdr-plugin-pulsectrl
  apt:
    name: '{{ item }}'
    state: present
    install_recommends: no
  with_items:
    - pulseaudio
    - pavucontrol
    - vdr-plugin-pulsectrl

- name: create /etc/asound.conf with pulseaudio as default device
  template:
    src: templates/alsa/asound.conf.j2
    dest: /etc/asound.conf
