---

- name: apt | install pulseaudio, pavucontrol and vdr-plugin-pulsecontrol
  apt:
    name:
      - pulseaudio
      - pavucontrol
      - vdr-plugin-pulsecontrol
    state: present
    install_recommends: no

- name: create /etc/asound.conf with pulseaudio as default device
  template:
    src: templates/alsa/asound.conf.j2
    dest: /etc/asound.conf
