- name: apt | ensure debconf and debconf-utils are installed
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - debconf
    - debconf-utils

- name: use bash instead of dash by default
  debconf:
    name: dash
    question: dash/sh
    value: 'false'
    vtype: select
- name: create vdr group
  group:
    gid: '{{ vdr.gid }}'
    state: present
    name: '{{ vdr.group }}'

- name: create vdr user
  user:
    name: '{{ vdr.user }}'
    group: '{{ vdr.group }}'
    uid: '{{ vdr.uid }}'
    home: '{{ vdr.home }}'
    shell: '/bin/bash'
    state: present
    append: true
- name: disable release-upgrade notifications
  lineinfile:
    dest: /etc/update-manager/release-upgrades
    backrefs: yes
    state: present
    regexp: '^(Prompt=).*$'
    line: '\1never'
  ignore_errors: yes
  with_first_found:
    - files:
      - /etc/update-manager/release-upgrades
      skip: true
- name: apt | install basic packages
  apt:
    name: '{{ item }}'
    state: present
    install_recommends: no
  with_items:
    - anacron
    - acl
    - at
    - bash-completion
    #- biosdevname  # caution: may change device names after a minimal installation!
    - debconf-utils
    - linux-firmware
    - psmisc
    - python-kmodpy
    - python-requests
    - python-usb
    - python3-usb
    - software-properties-common
    - ssh
    - wget
    - wpasupplicant
    - usbutils
    - xfsprogs
- name: apt | install extra packages
  apt:
    name: '{{ item }}'
    state: present
    install_recommends: no
  with_items:
      '{{ extra_packages }}'
