- name: ensure package cloud-config is not installed
  apt:
    name: cloud-init
    state: absent
- name: use bash instead of dash
  shell: |
    echo "set dash/sh false" | debconf-communicate
    dpkg-reconfigure -f noninteractive dash
- name: create vdr group
  group:
    gid: '{{ vdr.gid }}'
    state: present
    name: '{{ vdr.group }}'

- name: create vdr user
  user:
    name: '{{ vdr.user }}'
    group: '{{ vdr.group }}'
    uid: '{{ vdr.uid }}'
    home: '{{ vdr.home }}'
    shell: '/bin/bash'
    state: present
    append: true
- name: disable release-upgrade notifications
  lineinfile:
    path: /etc/update-manager/release-upgrades
    backrefs: yes
    state: present
    regexp: '^(Prompt=).*$'
    line: 'Prompt=never'
  ignore_errors: yes
- name: apt | install basic packages
  apt:
    name:
      - anacron
      - acl
      - at
      - bash-completion
      #- biosdevname  # caution: may change device names after a minimal installation!
      - debconf-utils
      - linux-firmware
      - psmisc
      - python3-jmespath
      - python-kmodpy
      - python-requests
      - python-usb
      - python3-usb
      - software-properties-common
      - ssh
      - wget
      - wpasupplicant
      - usbutils
      - xfsprogs
      - yavdr-i18n
    state: present
    install_recommends: no
- name: apt | install extra packages
  apt:
    name: '{{ extra_packages }}'
    state: present
    install_recommends: no
