- name: ensure /etc/yavdr exists
  file:
    path: /etc/yavdr
    state: directory
    mode: 0755

- name: touch /etc/yavdr/autoinstalled (this file must exist)
  file:
    path: /etc/yavdr/autoinstalled
    state: touch

- name: create media directories
  file:
    dest: '{{ item.value }}'
    owner: '{{ vdr.user }}'
    group: '{{ vdr.group }}'
    state: directory
    mode: '0777'
  loop: '{{ media_dirs|dict2items }}'
