- name: get information about usb and pci hardware and loaded kernel modules
  hardware_facts:
    usb: True
    pci: True
    modules: True
    gpus: True
    
- debug:
    var: '{{ item }}'
    verbosity: 1
  with_items:
    - usb
    - pci
    - gpus
    - modules
