---
# file: local_facts.yml
- name: create directory for local facts
  file:
    dest: /etc/ansible/facts.d
    state: directory

- name: copy facts script for USB- and PCI(e)-IDs
  copy:
    src: files/hardware.facts.py
    dest: /etc/ansible/facts.d/hardware.facts
    mode: '0775'

- name: get local facts
  setup:
