---
# file: roles/yavdr-common/tasks/main.yml 

- name: basic installation
  block:
        - import_tasks: configure_apt.yml
        - import_tasks: configure_system.yml
        - import_tasks: create_directories.yml
  tags: [install]
