---

# This playbook sets up the basic packages an directories for a yaVDR installation
# file: roles/yavdr-common/tasks/main.yml

- name: apt | prevent automatic installation of recommended packages
  template:
    src: templates/90-norecommends.j2
    dest: /etc/apt/apt.conf.d/90norecommends

- name: add yaVDR PPAs
  apt_repository:
      repo: '{{ item }}'
      state: present
      update_cache: yes
  with_items: '{{ repositories }}'

- name: upgrade existing packages
  apt:
      upgrade: dist
      update_cache: yes

- name: apt | install basic packages
  apt:
    name: '{{ item }}'
    state: present
    install_recommends: no
  with_items:
    - anacron
    - at
    - bash-completion
    - biosdevname
    - linux-firmware
    - psmisc
    - software-properties-common
    - ssh
    - ubuntu-drivers-common
    - wget
    - wpasupplicant
    - usbutils
    - xfsprogs

- name: create directory for local facts
  file:
    dest: /etc/ansible/facts.d
    state: directory

- name: copy facts script for USB- and PCI(e)-IDs
  copy:
    src: files/hardware.facts.py
    dest: /etc/ansible/facts.d/hardware.facts
    mode: '0775'

- name: copy facts script for Sat>IP server detection
  copy:
    src: files/satip.facts.py
    dest: /etc/ansible/facts.d/satip.facts
    mode: '0775'

- name: reload ansible local facts
  setup: filter=ansible_local
