- name: create /usr/local/bin/module-helper
  template:
    src: templates/module-helper.j2
    dest: /usr/local/bin/module-helper
    mode: '0755'

- name: create standby hooks /lib/systemd/system-sleep/yavdr
  template:
    src: templates/system-sleep_yavdr.j2
    dest: /lib/systemd/system-sleep/yavdr
    mode: '0755'
