---
# file roles/autoinstall-ubuntu-drivers/tasks/main.yml

- name: autoinstall ubuntu-drivers-common
  block:
    - name: apt | install ubuntu-drivers-common
      apt:
        name: ubuntu-drivers-common
        state: present

    - name: let ubuntu-drivers automatically install additional drivers
      command: ubuntu-drivers --package-list /etc/yavdr/autoinstalled autoinstall
  when:
    - ansible_virtualization_type != "virtualbox"
    - ansible_virtualization_role != "guest"
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version != "16.04"  # ubuntu-drivers-common tries to autoinstall
                                               # conflicting packages for virtualbox :(
