---
# file roles/autoinstall-ubuntu-drivers/tasks/main.yml

- name: autoinstall ubuntu-drivers-common
  block:
    - name: apt | install ubuntu-drivers-common
      apt:
        name: ubuntu-drivers-common
        state: present

    - name: use ubuntu-drivers to install additional drivers automatically
      command: ubuntu-drivers --package-list /etc/yavdr/autoinstalled autoinstall
  when: (ansible_virtualization_type != "virtualbox" and ansible_virtualization_role != "guest") or
        ansible_distribution_version != "16.04"
        # ubuntu-drivers-common tries to autoinstall
        # conflicting packages for virtualbox in Ubuntu 16.04 :(
