---
# this playbook sets up network services for a yaVDR installation
#
- name: install network packages
  apt:
      name: '{{ item }}'
      state: present
      install_recommends: no
  with_items:
      - avahi-daemon
      - avahi-utils
      - biosdevname
      - ethtool
      - nfs-common
      - vdr-addon-avahi-linker
      - wakeonlan

- name: install and configure nfs-kernel-server
  apt:
      name: "{{ item }}"
      state: present
      install_recommends: no
  with_items:
      - nfs-kernel-server
  when:
      - install_nfs_server

#- name: install and configure mariadb-server
#  apt:
#      name: "{{ item }}"
#      state: present
#      install_recommends: no
#  with_items:
#      - mariadb-server
#      - mariadb-client
#      - python-mysqldb
#  when:
#      - install_mariadb
#
#- name: create a new database with name epg2vdr
#  mysql_db:
#      name: epg2vdr
#      state: present
#      encoding: utf-8
#  when:
#      - install_mariadb
#
#  mysql_user:
#      name: epg2vdr
#      password: epg
#      priv: 'epg2vdr.*:ALL,GRANT'
#      host_all: yes
#      state: present
#  when:
#      - install_mariadb
#
#- name: Install and configure vdr-epg-daemon
#  apt:
#    name: "{{ item }}"
#    state: present
#    with_items:
#      - vdr-epg-daemon
#  when:
#      - install_epgd
