---
# file: roles/vdr-plugin-menuorg/tasks/main.yml

- name: apt | install vdr-plugin-menuorg
  apt:
    name:
      - vdr-plugin-menuorg
    state: present
    install_recommends: no

- name: create /var/lib/vdr/plugins/menuorg.xml
  template:
    src: templates/menuorg.xml.j2
    dest: /var/lib/vdr/plugins/menuorg.xml
    owner: "{{ vdr.user }}"
    group: "{{ vdr.group }}"
    mode: 0644
