---
# file roles/autoinstall-dvbsddevice/tasks/main.yml

# TODO: install firmware

- name: apt | install vdr-plugin-dvbsddevice if module is loaded
  apt:
    name:
      - vdr-plugin-dvbsddevice
      - yavdr-firmware
  when: '"dvb_ttpci" in modules'
  notify: [ 'Restart VDR' ]
