---

- name: apt | install kodi packages
  apt:
    name:
      - kodi
      - kodi-pvr-vdr-vnsi
      - python3-lxml
    state: present
    install_recommends: no

- name: apt | install kodi-send (team-xbmc PPA)
  apt:
    name: "kodi-eventclients-kodi"
    state: present
    install_recommends: no
  register: team_xbmc_ppa
  ignore_errors: True

- name: apt | install kodi-send (Ubuntu package)
  apt:
    name: "kodi-eventclients-xbmc-send" # fallback to old xbmc-send package
    state: present
    install_recommends: no
  when: team_xbmc_ppa.failed
