---

- name: apt | install kodi packages
  apt:
    name: '{{ item }}'
    state: present
    install_recommends: no
  with_items:
    - kodi
    - kodi-pvr-vdr-vnsi
    - kodi-eventclients-kodi-send # for ubuntu packages, team-xbmc uses "kodi-eventclients-xbmc-send for some reason
