---

- name: change udev rule to allow KODI to eject optical disks
  shell: sed 's/--lock-media //' /lib/udev/rules.d/60-cdrom_id.rules > /etc/udev/rules.d/60-cdrom_id.rules
  args:
    creates: /etc/udev/rules.d/60-cdrom_id.rules

- name: apt | install kodi packages
  apt:
    name: '{{ item }}'
    state: present
    install_recommends: no
  with_items:
    - kodi
    - kodi-pvr-vdr-vnsi
    - kodi-eventclients-xbmc-send  

- name: create kodi.service for the user session
  template:
      src: 'templates/kodi.service.j2'
      dest: '{{ vdr.home }}/.config/systemd/user/kodi.service'
      mode: 0755
      owner: '{{ vdr.user }}'
      group: '{{ vdr.group }}'

- name: create kodi user directory
  file:
      dest: '{{ vdr.home }}/{{ item }}'
      state: directory
      owner: '{{ vdr.user }}'
      group: '{{ vdr.group }}'
      mode: "0775"
  with_items:
      - .kodi
      - .kodi/userdata
      - .kodi/userdata/keymaps

# TODO: Add configuration files
