---
# file roles/autoinstall-hardware-irmp/tasks/main.yml

- name: apt | install yavdr-hardware-irmp if connected
  apt:
    name: yavdr-hardware-irmp
  when: '"1209:4444" in usb'
  notify: [ 'Restart VDR' ]
