---
# file roles/autoinstall-hardware-irmp/tasks/main.yml

- name: apt | install yavdr-hardware-irmp if connected
  apt:
    name: yavdr-hardware-irmp
    state: present
  when: '"1209:4444" in usb or "16c0:27d9" in usb'
