---
# file roles/autoinstall-virtualbox-guest/tasks/main.yml

- name: install virtualbox guest additions
  block:
    - name: install packages
      apt:
        state: present
        name:
          - dkms
          - virtualbox-guest-x11-hwe
          - virtualbox-guest-dkms-hwe
          - virtualbox-guest-x11-hwe

    # TODO: set xineliboutput as frontend
  when:
    - ansible_virtualization_type == "virtualbox"
    - ansible_virtualization_role == "guest"
    - ansible_distribution == "Ubuntu"

- name: set xineliboutput as frontend
  block:
    - apt:
        name:
          - vdr-plugin-xineliboutput
          - xineliboutput-sxfe
        state: present
    - command: '{{ item }}'
      with_items:
        - vdrctl disable softhddevice
        - vdrctl disable vaapidevice
        - vdrctl disable xine
        - vdrctl disable pvr350
        - vdrctl enable xineliboutput
      ignore_errors: yes
  when:
    - ansible_virtualization_type == "virtualbox" or ansible_virtualization_type == "VMware"
    - ansible_virtualization_role == "guest"
