---
# file roles/autoinstall-virtualbox-guest/tasks/main.yml

- name: install virtualbox guest additions
  block:
    - name: install packages
      apt:
        state: present
        name: '{{ item }}'
      with_items:
        - virtualbox-guest-dkms
        - virtualbox-guest-x11
        - dkms

    # TODO: set xineliboutput as frontend
  when:
    - ansible_virtualization_type == "virtualbox"
    - ansible_virtualization_role == "guest"
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version == "16.04"

- name: set xineliboutput as frontend
  command: '{{ item }}'
  with_items:
    - vdrctl disable softhddevice
    - vdrctl disable vaapidevice
    - vdrctl disable xine
    - vdrctl disable pvr350
    - vdrctl enable xineliboutput
  ignore_errors: yes
  when:
    - ansible_virtualization_type == "virtualbox"
    - ansible_virtualization_role == "guest"
