---
# file roles/autoinstall-DVBSky-S952/tasks/main.yml

- name: Download firmware of DVBSky-S952 if detected to /lib/firmware and extract them
  unarchive:
    src: http://www.dvbsky.net/download/linux/dvbsky-firmware.tar.gz
    dest: /tmp/
    remote_src: yes
  when: 
      - '"1ade:3038" in pci' 
      - ansible_distribution_version >= '15.04'  #driver only included since Kernel 3.19

- name: Copy the required firmware to right folder
  copy:
    src: /tmp/dvbsky-firmware/dvb-demod-m88rs6000.fw
    dest: /lib/firmware/
    owner: root
    group: root
    mode: 0644

- name: Remove unnecessary files from download
  file: path=/tmp/dvbsky-firmware state=absent