---
# file: roles/serial-ir/tasks/main.yml
- name: check if serial_ir_device is not empty and does not match devices defined in serial_ir_data
  fail:
    msg: "The serial device  {{ serial_ir_device }} is not defined in serial_ir_data"
  when: serial_ir_device|length > 0 and serial_ir_device not in serial_ir_data

- name: apt | install setserial
  apt:
    name: setserial

- name: load serial_ir on startup
  template:
    src: roles/serial-ir/templates/modules-load.d/serial_ir.conf.j2
    dest: /etc/modules-load.d/serial_ir.conf

- name: serial_ir module options
  template:
    src: roles/serial-ir/templates/modprobe.d/serial_ir.conf.j2
    dest: /etc/modprobe.d/serial_ir.conf

- name: setserial options
  template:
    src: roles/serial-ir/templates/serial.conf.j2
    dest: /etc/serial.conf
