---

- name: add ppa:graphics-drivers/ppa
  apt_repository:
      repo: 'ppa:graphics-drivers/ppa'
      state: present
      update_cache: yes
  tags:
    - ppa

- name: install nvidia-430 and other required packages
  apt:
    name:
      - nvidia-driver-430
      - nvidia-settings
    state: present
    install_recommends: no
  tags:
    - packages
