---

- name: add ppa:graphics-drivers/ppa
  apt_repository:
      repo: 'ppa:graphics-drivers/ppa'
      state: present
      update_cache: yes
  tags:
    - ppa

- name: install nvidia-387 and other required packages
  apt:
    name: '{{ item }}'
    state: present
    install_recommends: no
  with_items:
    - nvidia-390
    - nvidia-settings
  tags:
    - packages
