---

# This role provides easyily downloadable firmware files

- name: Firmware for Hauppauge WinTV HD Solo/Duo, PCTV 292e
  get_url:
    url: https://github.com/OpenELEC/dvb-firmware/raw/master/firmware/dvb-demod-si2168-b40-01.fw
    checksum: sha256:8507536630d75a316d0719d6b95c04b90c36baa5b457ad457c9bacadafcef134
    dest: /lib/firmware/dvb-demod-si2168-b40-01.fw
  when: '"2040:0264" in usb or "2013:025f" in usb'

- name: Firmware for Hauppauge WinTV-HVR-930C
  get_url:
    url: https://github.com/OpenELEC/dvb-firmware/raw/master/firmware/dvb-fe-xc5000-1.6.114.fw
    checksum: sha256:7104bda8df301fe1bd4c09de1708aeb6d0d8e1f9d55505449fecfad82639235f
    dest: /lib/firmware/dvb-fe-xc5000-1.6.114.fw
  when: '"2040:1605" in usb'
