---
# file: roles/yavdr-xorg/tasks/main.yml
- import_tasks: setup-xorg.yml
  tags: [install,update]
- import_tasks: detect-xorg.yml
  tags: [xorg.detect,install]
- import_tasks: desktop-session.yml
  tags: [install,update]
