---

- name: install nfs server packages
  apt:
    name: '{{ item }}'
    state: present
    install_recommends: no
  with_items:
    - nfs-kernel-server
    - nfs-common

- name: create /etc/exports
  template:
    src: templates/nfs-exports.j2
    dest: /etc/exports
  notify: [ 'Restart NFS Kernel Server' ]

- name: populate /etc/avahi/services
  template:
    src: templates/avahi/service.j2
    dest: '/etc/avahi/services/yavdr-{{ item.key }}.service'
    with_dict: 
      - '{{ media_dirs }}'
