---

- name: install nfs server packages
  apt:
    name:
      - nfs-kernel-server
      - nfs-common
    state: present
    install_recommends: no

- name: create /etc/exports
  template:
    src: templates/nfs-exports.j2
    dest: /etc/exports
  notify: [ 'Restart NFS Kernel Server' ]

- name: populate /etc/avahi/services
  template:
    src: templates/avahi/service.j2
    dest: '/etc/avahi/services/yavdr-{{ item.key }}.service'
  loop: '{{ media_dirs|dict2items }}'
