---

- name: add ppa:graphics-drivers/ppa
  apt_repository:
      repo: 'ppa:graphics-drivers/ppa'
      state: present
      update_cache: yes

- name: install nvidia-381 and other required packages
  apt:
    name: '{{ item }}'
    state: present
    install_recommends: no
  with_items:
    - nvidia-381
    - nvidia-settings
